### ISSUE TITLE
No explicit license provided

### ISSUE THREAD

**Issue by charles-dyfis-net** [mindreframer/golang-devops-stuff#3]
At present, it's unclear whether and under what circumstances code given in this repository can be used by others.

Providing an explicit copyright statement and license would make it easier for others to determine whether they're able to leverage content found here.

**Comment by mindreframer** [comment]
Honestly, this is just aggregated collection of repositories from different maintainers, so the licence provided by each project applies to that code. And you should probably just use the code directly from respective github url, that you can find in 
`https://github.com/mindreframer/golang-devops-stuff/blob/master/projects.txt`

I hope it is clearer now. Cheers!
